name: Docker Custom Image CI GHCR
run-name: Build ${{ inputs.branch }} - ${{ inputs.user }}

on:
  push:
    branches:
      - master-noro
    tags:
      - v*
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Call Start URL - optionally
        if: ${{ github.event.inputs.start-url != '' }}
        run: curl -v -X POST -d 'url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}' ${{github.event.inputs.start-url}} || echo ""
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to GHCR
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set IMAGE_NAME_LOWER
        run: echo "IMAGE_NAME_LOWER=${IMAGE_NAME,,}" >> $GITHUB_ENV

      - name: Build and push image to GHCR
        uses: docker/build-push-action@v6.11.0
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          file: ./docker/images/n8n-custom/Dockerfile
          platforms: linux/amd64
          provenance: false
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.IMAGE_NAME_LOWER }}:latest,${{ env.IMAGE_NAME_LOWER }}:${{ github.sha }}

      - name: Call Success URL - optionally
        if: ${{ github.event.inputs.success-url != '' }}
        run: curl -v ${{github.event.inputs.success-url}} || echo ""
        shell: bash